### PR TITLE
migrate from public docker hub to factual registry

### PR DESCRIPTION
**Pull request by bilow-factual**

### CODE REVIEW

**Comment by worace** [comment]
So the base one already got moved to internal registry only? Doesn't exist on dockerhub anymore?

Are we going to then start pushing docker-cdh5-dev to only internal registry as well? Seems more or less OK but I wonder if we should care about random internal processes that fail without that image being available on public docker hub?

**Comment by ndigati** [comment]
Why are we switching this to the internal registry? Since it's open source we should probably be keeping it on the public docker hub. Also if we migrate to the internal registry we lose some nice features (like automated builds).

**Comment by bilow-factual** [comment]
Ah, ok, it was mostly an idea; the automated builds don't seem to be happening, because the builds point to boris's images rather than Factual's

see: https://hub.docker.com/r/factual/docker-base/

**Comment by bilow-factual** [comment]
Closing, but we should update the images on docker hub to point to the factual images rather than the bfs ones.

**Pull request closed without merging**
